### ISSUE TITLE
No 'version' key

### ISSUE THREAD

**Issue by DigitalWarrior** [finity69x2/nws_alerts#10]
Home Assistant is throwing a warning about not having a version key. 

No 'version' key in the manifest file for custom integration 'nws_alerts'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'nws_alerts'

**Comment by finity69x2** [comment]
have you updated to the latest version?

the version key is in there and has been for a while now.

**Comment by cbhiii** [comment]
Hi. Thanks for the work you've put into this custom package.

I just loaded the integration tonight and saw the same error pop up during HA Core boot-up. It's still a thing, or HA is still not seeing it. I'm using version 1.9.1 

`2021-05-21 21:37:07 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'keymaster'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'keymaster'`
