### ISSUE TITLE
NWS Alerts not showing up in Integrations

### ISSUE THREAD

**Issue by nelsontechnologies** [finity69x2/nws_alerts#12]
I have installed via HACS and it installs perfectly. However, after restarting, it is not showing up in integrations in the configuration UI section. Any ideas?

**Comment by finity69x2** [comment]
I'm not sure what you mean.

It's showing up in HACS on my install.

Sorry, I've been OOC/busy lately.

Is this resolved?

**Comment by firstof9** [comment]
They just have to hit `F5` to refresh the integrations section for it to show up.
