### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by DeadEnded** [finity69x2/nws_alerts#2]
I just wanted to share this issue from the HA logs.
If this can be ignored, feel free to close this issue.

Thanks,
DeadEnd

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 9:08:45 AM (1 occurrences)
Last logged: 9:08:45 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for nws_alerts doing I/O at custom_components/nws_alerts/sensor.py, line 126: r = requests.get(url, headers=headers)

**Comment by finity69x2** [comment]
TBH, I've never noticed that error in the logs before and I've been using the custom integration for a couple of years now.

So I don't *think* it should be a concern.

Maybe it was an issue with the nws website that was causing problems. That web service actually has problems quite a bit.

Please let me know if it continues tho or causes issues and I can try to see if I can figure out why.

**Comment by AkA57** [comment]
Hello,
It's happen with v0.109, check https://www.home-assistant.io/blog/2020/04/29/release-109/#detection-of-blocking-io-in-the-event-loop

**Comment by njchaltry** [comment]
I have the same exact error message. It occurs each time the server is restarted.

**Comment by finity69x2** [comment]
There is a PR in the works right now to help solver this issue. It should be tested & if all goes well it will be released in a day or two.

**Comment by finity69x2** [comment]
fixed with the PR
