### ISSUE TITLE
Error message in the Log  After Update to 2021.12.0 of Home Assistant

### ISSUE THREAD

**Issue by jweston2112** [finity69x2/nws_alerts#27]
Entity sensor.nws_alerts_for_hawkins_county (<class 'custom_components.nws_alerts.sensor.NWSAlertSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by finity69x2** [comment]
Thanks for the heads up.

I just made a change and it should be in HACS soon.

The error should be gone.

Give it a try and let me know if everything is still working OK for you.

**Comment by jweston2112** [comment]
Updated from HACS as Well as to HA 2021.12.1 and The Error message I sent has departed... :)
Living on a farm Rural TN ...you kinda need to know when there is nasty weather or a freeze warning....

Thank You

**Comment by jweston2112** [comment]
![Capture](https://user-images.githubusercontent.com/70152549/145854236-9bf98562-ede5-4527-92de-78872378707d.jpg)

I wanted to wait till I got an alert before closing...  but I got one and it seems to be working Great

Thank You Again!
