### ISSUE TITLE
Add display (lovelace config) info to the readme.

### ISSUE THREAD

**Issue by rct** [finity69x2/nws_alerts#29]
Thank you for this integration. Initially didn't see anything in this repo for how to use this integration.

* There's a broken link in the README, so I missed the the example config in the packages directory.
   * I think the link should be https://github.com/finity69x2/nws_alerts/blob/master/packages/nws_alerts_custom_package.yaml
* I only accidentally stumbled on the very useful conditional/markdown cards in a closed issue, (this was exactly what I was looking for.)  It would be helpful to add this to the README or the repo.
  * https://github.com/finity69x2/nws_alerts/issues/9#issuecomment-805992371

**Comment by finity69x2** [comment]
Done.

Thanks for pointing that out.

**Comment by rct** [comment]
Thanks.  BTW I thought 5 cards for displaying alerts might be excessive. This weekend with the nor'easter/blizzard we had in the US northeast, there were 7 active alerts.

Several were slightly redundant, because they had small differences for adjacent/overlapping areas.  I don't really have any ideas yet if there is anything to do about that.
