### ISSUE TITLE
Recent nws_alerts_custom_package.yaml update removes sensor

### ISSUE THREAD

**Issue by mattyams** [finity69x2/nws_alerts#32]
I noticed the other day that my alerts were not working so I checked to see if there were any updates around and I saw that your nws_alerts_custom_package.yaml was updated. However, in the file you removed the nws_alerts integration and replaced it with the weatheralerts integration. By doing this, sensor.nws_alerts is removed and sensor.<countyname> is added. 

Just curious if the nws_alerts integration is broken? If that is the case shouldn't there be some indication that sensor.nws_alerts has been replaced and the code updated to the new data being recieved?  I am guessing the weatheralerts sensor could just be renamed to sensor.nws_alerts but looking at the data sent by both integrations there are some discrepancies such as "title" being sent as "event_id" in nws_alerts and in weatheralerts the data appears to be 1:1.

**Comment by mattyams** [comment]
Dove into it further and realized that I had not set up the integration in the UI and only in the yaml. This should resolve my concerns with sensor.nws_alerts missing but still curious about the addition of weatheralerts.

**Comment by finity69x2** [comment]
Sorry about that.

I had another user post an issue but they were using the old (really old) version of the api implementation. So I updated the package to my latest so they could use it.

I have other stuff in the package on my own system besides the things directly related to my integration. I must have not edited it correctly. 

Thanks for pointing it out. I'll get it fixed soon.

**Comment by mattyams** [comment]
Nothing to be sorry for. I, like many before me I'm sure, did not fully read the documentation that nws_alerts could be installed using the HA UI after using HACS to install. Glad I was able to point it out for you.  Thanks for your work and great integration!
