### ISSUE TITLE
Unable to complete setup via the Homeassistant UI.

### ISSUE THREAD

**Issue by blindndangerous** [finity69x2/nws_alerts#33]
After installing through hacs and restarting, I went to configuration>integrations>add integration and found NWS Alerts.  It populated the zone ID's automatically, but when I press submit I get an error that says  Malformed User input: Expected STR for data zone ID.

**Comment by finity69x2** [comment]
I'm, looking into it right now but in the meantime all you need to do is just delete the last character in the zone list and re-type it and it should work fine.

example:

if the "Zone ID's" section is...

INC033,INZ009

...just delete the 9 from the end and re-type the 9 and hit submit and it should work.

**Comment by firstof9** [comment]
Should be fixed in #34

**Comment by finity69x2** [comment]
the release should be available in HACS soon
