### ISSUE TITLE
Using your config example

### ISSUE THREAD

**Issue by Vyloo** [finity69x2/nws_alerts#36]
I get this error on all the automation.

![image](https://user-images.githubusercontent.com/62805463/167491601-899020e6-5fdc-4651-a729-789bba11f8d9.png)

**Comment by Vyloo** [comment]
![image](https://user-images.githubusercontent.com/62805463/167492728-5ecf9937-def6-4de8-bb09-304acd64498b.png)
Also this issue?

**Comment by finity69x2** [comment]
for the first one above change 'on' to true.

I'm not sure if that was a recent change or not but mine are all still working with 'on'.

Or it could just be a quirk in the editor you are using flagging it unnecessarily.

as for the second one you need to install the "hass-variables" custom integration to use that code.

it can be found in HACS.

**Comment by Vyloo** [comment]
Also the siren or the Nws alert tone doesn’t seem to work either with this config not sure how to fix this

Sent from my iPhone

On May 13, 2022, at 1:32 PM, finity69x2 ***@***.***> wrote:

﻿

for the first one above change 'on' to true.

I'm not sure if that was a recent change or not but mine are all still working with 'on'.

Or it could just be a quirk in the editor you are using flagging it unnecessarily.

as for the second one you need to install the "hass-variables" custom integration to use that code.

it can be found in HACS.

**Comment by Vyloo** [comment]
![image](https://user-images.githubusercontent.com/62805463/168373483-5e8b44b2-fa3f-4df2-a2cf-b7401264f724.png)
I dont think that did the trick

**Comment by finity69x2** [comment]
You will have to come up with your own alert tone for this. It's not included in the repo.

I can try to add it so you can download it but it still will need to be copied over manually since it can't be installed with HACS.

**Comment by finity69x2** [comment]
I've added the file. it is in the www directory here and you need to add it to your www/mp3 directory in HA.

**Comment by Vyloo** [comment]
I was actually able to download it via the URL that was already in the yaml example.

Do they need to be individually listed for it to work? or can you do media_player.everywhere

![image](https://user-images.githubusercontent.com/62805463/168403282-2ffec517-9c06-4de7-8736-c10b0faea05e.png)

I've also tried experimenting with other configurations of this but it doesn't work.

**Comment by Vyloo** [comment]
`        data:
          message: "<audio src='https://h7a3u8r0lt405rwrar1rcgi8ep9a1gez.ui.nabu.casa/local/mp3/nws_alert_tone.mp3' />"
          target: 
            - media_player.computer_room_dot
            - media_player.kitchen_dot
            - media_player.garage_dot
            - media_player.basement_dot
            - media_player.sunroom_dot
            - media_player.livingroom_dot
          data:
            type: tts
      - delay: '00:00:25'`

The way you have it configured doesn't work for me, after I changed the targets.

**Comment by finity69x2** [comment]
You don't have the entity_id line and the entities under it indented enough. They need to be two more spaces to the right.
