### ISSUE TITLE
Additional Attributes?

### ISSUE THREAD

**Issue by majorsl** [finity69x2/nws_alerts#4]
Hey, this works pretty well!  THANK YOU!  Is there any chance more of the attributes can be added from the feed?  severity, certainty, and instruction are a few of them I'd be interested in.

**Comment by finity69x2** [comment]
"instruction" is already added to the end of the display description (display_desc) if there is one included in the alert.

I can see what I can do to get the others added.

**Comment by finity69x2** [comment]
I've put the requested info into the integration.

it is in v1.3.
