### ISSUE TITLE
Change to Arrays

### ISSUE THREAD

**Issue by Snuffy2** [finity69x2/nws_alerts#40]
I recently cloned this and modified it to use Arrays. 
I added and slightly changed some of the attribute fields including headline, expiration, and instruction
I also updated the persistent and push notifications to be cleared once they expire.

If there's interest from @finity69x2, I can put it into a PR. Obviously it would be a large change and likely break all existing automations, scripts, etc.

I did not update the lovelace tab but could if needed.

If not, no worries at all, just figured I'd put it out there.

**Comment by Snuffy2** [comment]
[https://github.com/Snuffy2/nws_alerts/tree/change-to-arrays](url)

**Comment by finity69x2** [comment]
I just tried out your version with a location that had 4 alerts.

I think I like the way my attributes data is displayed and broken up in the states page. Only having things broken up by commas makes the individual pieces harder to read.

I think that the way I have my attributes may (may...) even make it a bit easier to template the data as well.

and I abhor breaking changes and unless there is a clear and definitive improvement in functionality I stay away from making those changes.

Thanks for putting it out there tho. I appreciate it. It's just not something I'm interested in changing right now.
