### ISSUE TITLE
Inconsistent Entry Separator for event id's

### ISSUE THREAD

**Issue by coaster3000** [finity69x2/nws_alerts#47]
https://github.com/finity69x2/nws_alerts/blob/master/custom_components/nws_alerts/__init__.py#L236

The entry is inconsistent with other attributes. Unsure if this was intentional or not.

Apologies for the sudden issue submission, I did not intend to submit it without information but the website had inadvertently submitted the issue on me while editing on mobile

**Comment by finity69x2** [comment]
Thanks for the heads up.

I fixed it so it should be in HACS soon if you use it.
