### ISSUE TITLE
New error on 2023.2 on the integration which states it will fail in 2023.3

### ISSUE THREAD

**Issue by Daali** [finity69x2/nws_alerts#51]
I am sure you know about it from the pull, but I did not see anyone post from the 2023.2 logs yet.  Sorry if this is just noise.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 8:48:09 PM (3 occurrences)
Last logged: 8:49:25 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nws_alerts using this method at custom_components/nws_alerts/__init__.py, line 68: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for auto_backup using this method at custom_components/auto_backup/__init__.py, line 192: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for garmin_connect using this method at custom_components/garmin_connect/__init__.py, line 40: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by finity69x2** [comment]
Thanks for the heads up.

I just released an update that (I hope ;) ) fixes it.
