### ISSUE TITLE
Enhancement: Alert targeting using FIPS zone alone results in false alarm potential

### ISSUE THREAD

**Issue by 303Bryan** [finity69x2/nws_alerts#53]
**Problem**: Using the NWS FIPS code results in monitoring relatively large geographic areas in some parts of the country. This results in the possibility of false triggers when the hazardous weather is not a threat to your location.

Here's a crude example of the issue I commonly encounter:
![image](https://user-images.githubusercontent.com/10273380/219960748-3deaacb0-d35f-4d0c-95fa-447583fd2531.png)
Yellow Star = Home Location (_example only_)
Purple Box = FIPS Zone
Blue Cloud = Storm System / Example Polygon
Blue Arrow = Direction of storm travel (the assumption that future alerts would be issued along this path) 

**Potential Solutions:** The NWS includes alert area polygon data in issued alerts. The NWS API also allows for point-based queries for severe threats. However, as others have pointed out in the [Home Assistant Community](https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853/396?u=bryan_fleming), there are drawbacks to using this data/implementing a solution. 

Reference:
[NWS Watch, Warning, and Advisory Geolocation](https://www.weather.gov/media/documentation/docs/NWS_Geolocation.pdf)

**Comment by finity69x2** [comment]
complete using the new coordinates integration.
