### ISSUE TITLE
Open up commits?

### ISSUE THREAD

**Issue by mdecourcy** [finity69x2/nws_alerts#55]
Hi there, I was having issues with the NWS_Alerts tab. Wanted to commit and create a PR with my changes but was met with a 403 forbidden. Thanks for providing this integration!

**Comment by finity69x2** [comment]
I'm not sure what you mean but you can open a PR if you want.

you just can't commit the changes yourself.

what is the issue you are having?

**Comment by mdecourcy** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/49794076/226771906-b1f60e3f-dfb5-4292-92fa-5bd3c662aff4.png">
Might just be an issue with my locally saved creds on this machine, I'll check after I wrap up at work

**Comment by jarrodsfarrell** [comment]
@mdecourcy You're trying to push directly to someone else's repo you do not have access to. You have to fork, clone your fork, branch, commit, push, then PR.

The flow I use to committing and PRing to someone else's project is the following:

- Through GitHub web, you fork the repo. This makes a personal copy for yourself.
- You clone your fork.
- Create a new branch from `main`/`master` or some other branch of interest.
- Make your commits
- Push
- Visit your repo and you should get a yellow banner indicating you can PR your changes.

This is my flow, but I know there's quicker ways via [GitHub's CLI](https://cli.github.com/manual/gh) and different ways to begin a PR. Explore around.

You will occasionally have to update your fork and there's a way to do it on the web, but typically I set up another remote on my local repo—like `upstream`—and use `git merge upstream` or something of that effect.

**Comment by mdecourcy** [comment]
Ah I see, my mistake! First attempt at open source contributions. I'm used to just feature branching and PRing at work. I'll fork and make a PR now.

**Comment by jarrodsfarrell** [comment]
@mdecourcy No problem, and that would be a valid way to do a PR as well on repos you have access to as well.
