### ISSUE TITLE
NWS Update Event ID Variable stopped working

### ISSUE THREAD

**Issue by bmcbmc34** [finity69x2/nws_alerts#6]
After HA 105 update  the Variable ID automation no longer worked for me.
Here is a fix for the Issue.
- alias: NWS Update Event ID Variable
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.nws_alerts
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state != 'Unknown' }}"
  action:
    service: variable.set_variable
    data:
      variable: nws_alerts_event_ids
      attributes_template: >
        {
          "history_1":"{{states('variable.nws_alerts_event_ids')}}",
          "history_2":"{{state_attr('variable.nws_alerts_event_ids','history_1')}}",
          "history_3":"{{state_attr('variable.nws_alerts_event_ids','history_2')}}",
          "history_4":"{{state_attr('variable.nws_alerts_event_ids','history_3')}}",
          "history_5":"{{state_attr('variable.nws_alerts_event_ids','history_4')}}",
          "history_6":"{{state_attr('variable.nws_alerts_event_ids','history_5')}}",
          "history_7":"{{state_attr('variable.nws_alerts_event_ids','history_6')}}",
          "history_8":"{{state_attr('variable.nws_alerts_event_ids','history_7')}}",
          "history_9":"{{state_attr('variable.nws_alerts_event_ids','history_8')}}",
          "history_10":"{{state_attr('variable.nws_alerts_event_ids','history_9')}}"
        }
   # data_template:
      value: "{{ (trigger.to_state.attributes.event_id).split('-')[0] }}"

**Comment by finity69x2** [comment]
Not really an issue with my integration, per se so I'm closing this one.

But thanks for pointing it out.

And as an FYI this is also completely different now with the new template engine in the latest version of HA.
