### ISSUE TITLE
Multiple alerts concatenated into long strings

### ISSUE THREAD

**Issue by disconn3ct** [finity69x2/nws_alerts#66]
In my region we frequently get overlapping alerts with the same data, but this occurs even with multiple distinct alerts. I've checked upstream and they are being issued as separate items.

For example, due to the wildfires there are several overlapping air quality emergencies as well as special weather statements with the same information. Instead of receiving an array with each alert as an 'object', it is only returning single long strings:
```
title: Air Quality Alert - Air Quality Alert - Special Weather Statement - Air Quality Alert - Air Quality Alert - Special Weather Statement - Air Quality Alert - Air Quality Alert
message_type: Alert - Alert - Alert - Alert - Alert - Alert - Alert - Alert - Alert
event_status: Actual - Actual - Actual - Actual - Actual - Actual - Actual - Actual - Actual
```

I would expect arrays of attributes, similar to other multi-value integrations (especially weather). I haven't come across any other cases where I need to deserialize data from a sensor.

**Comment by JakeHertenstein** [comment]
I have encountered this issue as well. Also, the implementation with concatenation makes it quite difficult to parse out attributes for a given alert.
I would like to suggest an alternative solution - add a service that responds with an appropriate data, [new in 2023.7](https://www.home-assistant.io/blog/2023/07/05/release-20237/#services-can-now-respond), structure would make it possible for automations to react to the data they need. I found a way to do this with custom templates but I had to jump through a lot of hoops to make it possible.

**Comment by AD-Wright** [comment]
How are you currently parsing?  The example (https://github.com/finity69x2/nws_alerts/blob/master/lovelace/alerts_tab) seems to use a built-in function: `state_attr('sensor.nws_alerts', 'title').split(' - ')[alert_num]`

**Comment by kevinhaas** [comment]
The attribute should be an array of alert entities.

**Comment by finity69x2** [comment]
This will be fixed in the next release

**Comment by jhemak** [comment]
@disconn3ct - did you ever come up with logic to filter out overlapping/redundant Air Quality Alerts and Special Weather Statements?

**Comment by disconn3ct** [comment]
No, I walked away from whole mess and haven't gotten back to it since it was fixed.

**Comment by jhemak** [comment]
OK - if you do ever get back to it I'd be interested in your solution.  I would like to display only the most recently-issued Air Quality Alert for my area and also reduce the state (count) to not count old/superseded alerts that are still coming from the NWS API.  I'll also share anything I come up with if I get to it first.
