### ISSUE TITLE
Please consider adding 'onset' as an attribute

### ISSUE THREAD

**Issue by kidhasmoxy** [finity69x2/nws_alerts#67]
The integration is fantastic and I'm using it for automations, but I've noticed that we'll often times have an alert long before the event in question. This is especially common for "watch" alerts.

I use this integration to trigger charging up my batteries to full and also certain other safety related items. Sometimes the onset is set as 24-36 hours after the alert starts, even when the alert is marked as severe. With the onset, I could decide when to start filling the batteries and also trigger certain automations for closer to the event vs the 1-2 days before where it's still sunny.

**Comment by jhemak** [comment]
I was about to suggest the same and then came across this.  +1 for the suggestion, please.  I would also like to suggest adding "ends" as I am seeing examples where the "ends" value and what is currently provided as "event expires" do not match.  Thank you!

**Comment by finity69x2** [comment]
I'll get this added soon. Sorry it's taken so long to implement.

**Comment by finity69x2** [comment]
Done

**Comment by jhemak** [comment]
Are you open to also adding "ends" as suggested above?  I have added it to mine manually but have to re-do the change every time you release an update to the integration.
