### ISSUE TITLE
How to configure poll rate and timeout in manual config

### ISSUE THREAD

**Issue by mikegoubeaux** [finity69x2/nws_alerts#68]
Awesome integration!

Wondering if you can manually configure the update and timeout if adding the integration via configuration.yaml?

**Comment by Rockstar04** [comment]
The config keys and default values are in the [const.py file](https://github.com/finity69x2/nws_alerts/blob/master/custom_components/nws_alerts/const.py)

Here is an example:
```
- platform: nws_alerts
  zone_id: 'PAC049'
  interval: 15
  timeout: 300
```
