### ISSUE TITLE
Documentation information

### ISSUE THREAD

**Issue by felafel** [finity69x2/nws_alerts#73]
Your example uses custom cards but there are no links to them.  Please put links to them in your documentation.

type: custom:vertical-layout
type: custom:stack-in-card
type: custom:entity-attributes-card

Thanks

**Comment by jswalls110** [comment]
+1

**Comment by finity69x2** [comment]
Done

**Comment by felafel** [comment]
This page https://github.com/finity69x2/nws_alerts has a link to https://github.com/finity69x2/nws_alerts/blob/master/lovelace/alerts_tab which does not exist for us.
