### ISSUE TITLE
FR: Filter NWS alerts by type to avoid displaying alerts of no interest

### ISSUE THREAD

**Issue by alexruffell** [finity69x2/nws_alerts#81]
I keep getting Amber and Silver alerts multiple times a week, and would like to filter them out. I only want severe weather alerts to filter through but cannot find a way to do so. My Samsung phone gives me the ability to select the categories I want leading me to believe there may be some data in the alert that one can use to filter what alerts to allow through. 

![image](https://github.com/finity69x2/nws_alerts/assets/4006944/db8f0ae8-9454-4e17-b8ed-37529225033c)

Can this be implemented?

**Comment by finity69x2** [comment]
I'm sorry but that screenshot has nothing at all to do with this integration. And I can't even tell you which integration that might even be.

**Comment by alexruffell** [comment]
@finity69x2 The screenshot is just to show an example of what I am talking about. NWS leveraging the NWS Alert system to not only warn about weather conditions but also Silver and Amber alerts. I was hoping for a filter, similar to what is shown in the screenshot, to eliminate all non weather related alerts.
