### ISSUE TITLE
Zone or County ID

### ISSUE THREAD

**Issue by vautieri** [finity69x2/nws_alerts#88]
Just curious if this is using some older api the weather service offered for location.  I see they are using CAPs when I go to the link mentioned to look up a zone or county id, but the link for these lists mentioned doesn't seem to exist.  I see home assistant has these already filled in for me so I'm going to assume it might be working, but I don't know how to test unless I figure out how to set my location where alerts exist.

**Comment by finity69x2** [comment]
Yeah, thanks for pointing that out to me. 

Obviously I haven't needed to use that link in a while and it doesn't work as I remember it.

I'll get the instructions updated in the readme for it but in the meantime you can find your zone by clicking on "Land areas with zones", then scroll down to your state, then click on either "public zones" or "county zones". Then scroll to find your location from the list(s).

As far as the other question as far as I know the automatically filled location data should still be correct.

I'll definitely need top keep an eye on this to see if any future changes may break things but for now everything still seems to be working.
