### ISSUE TITLE
Include 'ends' data with each event

### ISSUE THREAD

**Issue by GreyBandit** [finity69x2/nws_alerts#92]
Each event from the NWS includes an 'ends' string that differs from the 'expires' string. While 'expires' seems intuitive, it actually isn't what the NWS uses as the public end time of events (at least, not always). It would be helpful to include that data in the integration.

# Example
My area has an Excessive Heat Warning running from 1pm to 8pm on Aug 26, as seen here by the local NWS office website.
![image](https://github.com/user-attachments/assets/03191a7e-660d-44c1-b2a7-7c3aea3b13cb)

And here is the data from the NWS API (full data file linked below):
![image](https://github.com/user-attachments/assets/3c9f2505-0096-4528-9ab3-513334f5b735)
[NWSAlertData.txt](https://github.com/user-attachments/files/16743736/NWSAlertData.txt)

Notice how the 'ends' and 'expires' time are different. The 'expires' time is 5:45am Aug 26, while the 'ends' time is 8pm Aug 26. 8pm makes a lot more sense and is the time used and advertised by the NWS. It would really nice to have that string available in the Home Assistant integration.

**Comment by jhemak** [comment]
Yes please!  I made a similar comment in #67.  Thank you!

BTW, from what I have observed, ends is the better value to use for the end time of an alert; and when it's blank/missing, then it's best to use expires.

**Comment by finity69x2** [comment]
@GreyBandit and @jhemak (or anyone who comes around later...)

see the official NWS Alerts thread on the HA forum for further discussion on this issue:

https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853/596

**Comment by finity69x2** [comment]
added in latest release

**Comment by jhemak** [comment]
Thank you!!
