### ISSUE TITLE
Alexa wont play the local alert tone

### ISSUE THREAD

**Issue by beyondunreal79** [finity69x2/nws_alerts#94]
I can't seem to get my alexa devices to play the weather alert tone.  All it says is " Sorry I'm having trouble accessing your Simon says na skill right now".  I know the file is accessible from the outside using my link as its placed in my www folder.  Has anyone gotten this to work?

**Comment by finity69x2** [comment]
I've been using the nws alert tone literally for as long as I've been using this integration and I've never had any issues.

I even just tested it again and it worked fine so it has to be your system that has the issue.

I had someone recently say that they couldn't get some stuff to work and it was a cloudflare issue. maybe something like that is blocking it?

and are you sure you have the service call to the mp3 set up correctly?
